# Generated by Django 4.0.4 on 2022-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_remove_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-04-21'),
            preserve_default=False,
        ),
    ]
