# Generated by Django 4.0.4 on 2022-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0009_alter_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
